Config = {}

Config.SellValue = 0.55  -- 55% resale

-- ── Dealerships ──────────────────────────────────────────────────────────────
-- Each dealership filters vehicles by 'dealer' field.
-- Use the real GTA5 building entrances / curb positions.
Config.Dealerships = {
    {
        id       = 'pdm',
        label    = 'Premium Deluxe Motorsport',
        desc     = 'Sports & Coupes',
        pos      = vector3(-46.4, -1097.0, 26.4),
        spawnPos = vector3(-32.0, -1087.0, 26.4),
        blipIcon = 326, blipColour = 3,
        filter   = { 'Sports', 'Coupe' },
    },
    {
        id       = 'legendary',
        label    = 'Legendary Motorsport',
        desc     = 'Supercars & Hypercars',
        pos      = vector3(-323.0, -939.0, 28.0),   -- Vinewood / Alta area showroom
        spawnPos = vector3(-310.0, -929.0, 28.0),
        blipIcon = 326, blipColour = 1,
        filter   = { 'Supercar' },
    },
    {
        id       = 'southern',
        label    = 'Southern SA Super Autos',
        desc     = 'Sedans, SUVs & Economy',
        pos      = vector3(860.0, -2090.0, 29.0),   -- La Mesa near airport
        spawnPos = vector3(875.0, -2080.0, 29.0),
        blipIcon = 326, blipColour = 5,
        filter   = { 'Sedan', 'SUV', 'Economy', 'Van' },
    },
    {
        id       = 'bennys',
        label    = "Benny's Original Motor Works",
        desc     = 'Muscle & Custom Builds',
        pos      = vector3(-204.0, -1315.0, 31.4),  -- Strawberry / Forum Drive
        spawnPos = vector3(-195.0, -1304.0, 31.4),
        blipIcon = 326, blipColour = 40,
        filter   = { 'Muscle', 'Lowrider' },
    },
    {
        id       = 'lscycles',
        label    = 'Los Santos Cycles',
        desc     = 'Motorcycles & Bikes',
        pos      = vector3(-1271.0, -1285.0, 5.0),  -- Vespucci Canals / Del Perro
        spawnPos = vector3(-1260.0, -1275.0, 5.0),
        blipIcon = 226, blipColour = 27,
        filter   = { 'Motorcycle' },
    },
    {
        id       = 'patriot',
        label    = 'Patriot Motors',
        desc     = 'Trucks, Vans & Commercial',
        pos      = vector3(-168.0, 6326.0, 31.5),   -- Paleto Bay lot
        spawnPos = vector3(-157.0, 6316.0, 31.5),
        blipIcon = 326, blipColour = 4,
        filter   = { 'Truck', 'Commercial', 'Van' },
    },
    {
        id       = 'elitas',
        label    = 'Elitas Travel',
        desc     = 'Helicopters & Aircraft',
        pos      = vector3(-1336.0, -3044.0, 13.9), -- LSIA Terminal
        spawnPos = vector3(-1320.0, -3034.0, 13.9),
        blipIcon = 423, blipColour = 13,
        filter   = { 'Helicopter', 'Plane' },
    },
    {
        id       = 'boatclub',
        label    = 'Vespucci Boat Club',
        desc     = 'Boats & Watercraft',
        pos      = vector3(-808.0, -1330.0, 4.0),   -- Vespucci Beach marina
        spawnPos = vector3(-798.0, -1320.0, 1.0),
        blipIcon = 427, blipColour = 3,
        filter   = { 'Boat' },
    },
}

-- Garage (retrieve owned vehicles)
Config.GaragePos   = vector3(-351.0, -133.0, 39.0)
Config.GarageSpawn = vector3(-345.0, -127.0, 39.0)

-- ── Full GTA 5 Vehicle List ───────────────────────────────────────────────────
-- { model, label, price, category, dealer, desc }
-- dealer matches Dealerships[].id
Config.Vehicles = {

  -- ══ SUPERCARS ══
  { model='adder',       label='Truffade Adder',           price=1000000, category='Supercar', dealer='legendary', desc='The fastest production car in LS.' },
  { model='autarch',     label='Progen Autarch',            price=795000,  category='Supercar', dealer='legendary', desc='Track-optimised mid-engine monster.' },
  { model='bullet',      label='Vapid Bullet',              price=155000,  category='Supercar', dealer='legendary', desc='American V8 supercar icon.' },
  { model='cheetah',     label='Grotti Cheetah',            price=650000,  category='Supercar', dealer='legendary', desc='Italian thoroughbred supercar.' },
  { model='deveste8',    label='Överflöd Deveste Eight',    price=1795000, category='Supercar', dealer='legendary', desc='Ultra-aggressive hypercar.' },
  { model='entityxf',    label='Overflöd Entity XF',        price=795000,  category='Supercar', dealer='legendary', desc='Swedish hypercar, stunning lines.' },
  { model='entity2',     label='Overflöd Entity XXR',       price=2305590, category='Supercar', dealer='legendary', desc='Track monster, open cockpit.' },
  { model='fmj',         label='Pegassi FCR 1000',          price=1590000, category='Supercar', dealer='legendary', desc='Carbon-fibre Italian missile.' },
  { model='furia',       label='Pegassi Furia',             price=1995000, category='Supercar', dealer='legendary', desc='Extreme aerodynamic V12.' },
  { model='ignus',       label='Pfister Ignus',             price=2995000, category='Supercar', dealer='legendary', desc='Hybrid German performance pinnacle.' },
  { model='infernus',    label='Pegassi Infernus',          price=440000,  category='Supercar', dealer='legendary', desc='Classic Italian racer.' },
  { model='italigtb',    label='Grotti Itali GTB',          price=1189000, category='Supercar', dealer='legendary', desc='Mid-engine Italian elegance.' },
  { model='italigtb2',   label='Grotti Itali GTB Custom',   price=1235000, category='Supercar', dealer='legendary', desc='Track edition with open cockpit.' },
  { model='krieger',     label='Pfister Krieger',           price=2875000, category='Supercar', dealer='legendary', desc='German hypercar with F1 heritage.' },
  { model='neon',        label='BF Dune FAV',               price=525000,  category='Supercar', dealer='legendary', desc='Electric hypercar concept.' },
  { model='nero',        label='Truffade Nero',             price=1440000, category='Supercar', dealer='legendary', desc='Retro-inspired French GT.' },
  { model='nero2',       label='Truffade Nero Custom',      price=1470000, category='Supercar', dealer='legendary', desc='Open-top French GT masterpiece.' },
  { model='osiris',      label='Pegassi Osiris',            price=1950000, category='Supercar', dealer='legendary', desc='Exotic prototype racer.' },
  { model='penetrator',  label='Annis Penetrator',          price=875000,  category='Supercar', dealer='legendary', desc='Japanese-inspired sleek racer.' },
  { model='pfister811',  label='Pfister 811',               price=1135000, category='Supercar', dealer='legendary', desc='Turbocharged Porsche-style beast.' },
  { model='reaper',      label='Pegassi Reaper',            price=1595000, category='Supercar', dealer='legendary', desc='Aggressive mid-engine Italian.' },
  { model='sc1',         label='Vysser Neo',                price=1795000, category='Supercar', dealer='legendary', desc='Futuristic electric supercar.' },
  { model='t20',         label='Progen T20',                price=2200000, category='Supercar', dealer='legendary', desc='F1-inspired track weapon.' },
  { model='taipan',      label='Annis Taipan',              price=1895000, category='Supercar', dealer='legendary', desc='Australian-inspired track monster.' },
  { model='tempesta',    label='Pegassi Tempesta',          price=1329000, category='Supercar', dealer='legendary', desc='Targa-top Italian beauty.' },
  { model='thrax',       label='Pegassi Thrax',             price=2325000, category='Supercar', dealer='legendary', desc='Brutal Italian hypercar.' },
  { model='tigerb',      label='Buckingham Gran Turismo',   price=975000,  category='Supercar', dealer='legendary', desc='British Grand Tourer.' },
  { model='torero',      label='Pegassi Torero',            price=2950000, category='Supercar', dealer='legendary', desc='Classic Italian prancing horse.' },
  { model='tyrant',      label='Progen Tyrant',             price=2515000, category='Supercar', dealer='legendary', desc='Carbon fibre racing perfection.' },
  { model='vagner',      label='Progen Vagner',             price=1535000, category='Supercar', dealer='legendary', desc='Mid-engine aero-focused racer.' },
  { model='visione',     label='Grotti Visione',            price=2250000, category='Supercar', dealer='legendary', desc='Italian concept car made real.' },
  { model='xa21',        label='Grotti X80 Proto',          price=2700000, category='Supercar', dealer='legendary', desc='Prototype hypercar of the future.' },
  { model='zentorno',    label='Pegassi Zentorno',          price=725000,  category='Supercar', dealer='legendary', desc='Italian hypercar with dual wings.' },
  { model='zorrusso',    label='Truffade Thrax',            price=2325000, category='Supercar', dealer='legendary', desc='Hand-built Italian track GT.' },

  -- ══ SPORTS ══
  { model='alpha',       label='Karin Alpha',               price=150000,  category='Sports', dealer='pdm', desc='Lightweight Japanese sports car.' },
  { model='banshee',     label='Bravado Banshee',           price=126000,  category='Sports', dealer='pdm', desc='American V8 sports legend.' },
  { model='bestiagts',   label='Grotti Bestia GTS',         price=1090000, category='Sports', dealer='pdm', desc='Fierce Italian V12 grand tourer.' },
  { model='blista2',     label='Dinka Blista Compact',      price=29000,   category='Sports', dealer='pdm', desc='Japanese hot hatch.' },
  { model='buffalo',     label='Bravado Buffalo',           price=50000,   category='Sports', dealer='pdm', desc='American muscle meets sport sedan.' },
  { model='buffalo2',    label='Bravado Buffalo S',         price=60000,   category='Sports', dealer='pdm', desc='Supercharged version of the classic.' },
  { model='buffalo3',    label='Bravado Buffalo STX',       price=2150000, category='Sports', dealer='pdm', desc='Race-tuned street weapon.' },
  { model='carbonizzare',label='Grotti Carbonizzare',       price=195000,  category='Sports', dealer='pdm', desc='Italian V8 targa top sports.' },
  { model='comet2',      label='Pfister Comet',             price=100000,  category='Sports', dealer='pdm', desc='German sports icon.' },
  { model='comet3',      label='Pfister Comet Retro',       price=310000,  category='Sports', dealer='pdm', desc='Classic 911-inspired.' },
  { model='comet5',      label='Pfister Comet S2',          price=998000,  category='Sports', dealer='pdm', desc='Lightweight track Comet.' },
  { model='comet6',      label='Pfister Comet S2 Cab',      price=1003000, category='Sports', dealer='pdm', desc='Open-air Comet track car.' },
  { model='coquette',    label='Invetero Coquette',         price=145000,  category='Sports', dealer='pdm', desc='Classic American Corvette-style.' },
  { model='coquette3',   label='Invetero Coquette D10',     price=565000,  category='Sports', dealer='pdm', desc='Premium road-focused Coquette.' },
  { model='cypher',      label='Karin Calico GTF',          price=1995000, category='Sports', dealer='pdm', desc='Twin-turbo JDM track legend.' },
  { model='elegy',       label='Annis Elegy Retro Custom',  price=904000,  category='Sports', dealer='pdm', desc='JDM icon, retro-tuned.' },
  { model='elegy2',      label='Annis Elegy RH8',           price=95000,   category='Sports', dealer='pdm', desc='Modern Japanese sports standard.' },
  { model='euros',       label='Annis Euros',               price=1800000, category='Sports', dealer='pdm', desc='Aerodynamic German-Japanese hybrid.' },
  { model='flashgt',     label='Annis ZR380',               price=1395000, category='Sports', dealer='pdm', desc='Extreme track wing monster.' },
  { model='formula',     label='Ocelot R88',                price=3500000, category='Sports', dealer='pdm', desc='Open-wheel Formula 1 racer.' },
  { model='formula2',    label='Ocelot Pariah',             price=1420000, category='Sports', dealer='pdm', desc='Fastest stock sports car.' },
  { model='fusilade',    label='Schyster Fusilade',         price=36000,   category='Sports', dealer='pdm', desc='Budget American sports car.' },
  { model='gt500',       label='Vapid GT500',               price=665000,  category='Sports', dealer='pdm', desc='American muscle race heritage.' },
  { model='imorgon',     label='Overflöd Imorgon',          price=2115000, category='Sports', dealer='pdm', desc='Swedish electric sports concept.' },
  { model='issi3',       label='Weeny Issi Classic',        price=595000,  category='Sports', dealer='pdm', desc='Mini-style classic racer.' },
  { model='jb700',       label='Albany JB 700',             price=350000,  category='Sports', dealer='pdm', desc='Classic British spy car.' },
  { model='jester',      label='Dinka Jester',              price=135000,  category='Sports', dealer='pdm', desc='Japanese sports roadster.' },
  { model='jester3',     label='Dinka Jester Classic',      price=780000,  category='Sports', dealer='pdm', desc='Old-school Jester, heavily tuned.' },
  { model='jugular',     label='Ocelot Jugular',            price=1225000, category='Sports', dealer='pdm', desc='Aggressive British sports GT.' },
  { model='kuruma',      label='Karin Kuruma',              price=95000,   category='Sports', dealer='pdm', desc='Armoured Japanese sports sedan.' },
  { model='locust',      label='Annis S80RR',               price=2575000, category='Sports', dealer='pdm', desc='Open-wheel endurance racer.' },
  { model='lynx',        label='Ocelot Lynx',               price=1625000, category='Sports', dealer='pdm', desc='British precision in sports form.' },
  { model='massacro',    label='Dewbauchee Massacro',       price=260000,  category='Sports', dealer='pdm', desc='Aston-style British GT racer.' },
  { model='massacro2',   label='Dewbauchee Massacro Racecar',price=500000, category='Sports', dealer='pdm', desc='Full race-spec Massacro.' },
  { model='mamba',       label='Declasse Mamba',            price=1100000, category='Sports', dealer='pdm', desc='Open-wheel classic racer.' },
  { model='ninef',       label='Übermacht Oracle XS',       price=76000,   category='Sports', dealer='pdm', desc='BMW M3-style German sports.' },
  { model='ninef2',      label='Übermacht Sentinel XS',     price=66000,   category='Sports', dealer='pdm', desc='Compact German sports.' },
  { model='omnis',       label='Karin Futo GTX',            price=1590000, category='Sports', dealer='pdm', desc='Rally-spec JDM drift machine.' },
  { model='pariah',      label='Ocelot Pariah',             price=1420000, category='Sports', dealer='pdm', desc='Fastest sports car in class.' },
  { model='penumbra',    label='Imponte Penumbra',          price=46000,   category='Sports', dealer='pdm', desc='Budget Eclipse-inspired sports.' },
  { model='previon',     label='Karin Previon',             price=1795000, category='Sports', dealer='pdm', desc='JDM lightweight masterpiece.' },
  { model='rapidgt',     label='Dewbauchee Rapid GT',       price=130000,  category='Sports', dealer='pdm', desc='British open-top sports roadster.' },
  { model='revolter',    label='Übermacht Revolter',        price=1985000, category='Sports', dealer='pdm', desc='German performance four-door.' },
  { model='ruston',      label='Declasse DR1',              price=2265000, category='Sports', dealer='pdm', desc='Open-wheel endurance racer.' },
  { model='schlagen',    label='Pfister Schlagen GT',       price=1764000, category='Sports', dealer='pdm', desc='German touring perfection.' },
  { model='specter',     label='Ocelot Specter',            price=749000,  category='Sports', dealer='pdm', desc='Clean British open-top GT.' },
  { model='specter2',    label='Ocelot Specter Custom',     price=775000,  category='Sports', dealer='pdm', desc='Tweaked track-focused Specter.' },
  { model='sultan',      label='Karin Sultan',              price=35000,   category='Sports', dealer='pdm', desc='JDM sports standard.' },
  { model='sultan2',     label='Karin Sultan Classic',      price=895000,  category='Sports', dealer='pdm', desc='Classic JDM Sultan fully restored.' },
  { model='sultan3',     label='Karin Sultan RS Classic',   price=1700000, category='Sports', dealer='pdm', desc='Maximum attack Sultan.' },
  { model='surano',      label='Grotti Surano',             price=119000,  category='Sports', dealer='pdm', desc='Italian open-top roadster.' },
  { model='tropos',      label='Benefactor Streiter',       price=1795000, category='Sports', dealer='pdm', desc='German touring sport coupe.' },
  { model='verlierer2',  label='Benefactor Schwartzer',     price=132000,  category='Sports', dealer='pdm', desc='Aggressive German sports coupe.' },
  { model='zr350',       label='Annis ZR350',               price=1695000, category='Sports', dealer='pdm', desc='Japanese drift icon.' },
  { model='zr380',       label='Annis ZR380',               price=1395000, category='Sports', dealer='pdm', desc='Track-spec ZR with wing.' },

  -- ══ MUSCLE ══
  { model='blade',       label='Vapid Blade',               price=32000,  category='Muscle', dealer='bennys', desc='Classic American streetrod.' },
  { model='buccaneer',   label='Albany Buccaneer',          price=35000,  category='Muscle', dealer='bennys', desc='Big block American classic.' },
  { model='buccaneer2',  label='Albany Buccaneer Custom',   price=115000, category='Muscle', dealer='bennys', desc='Lowrider-tuned Buccaneer.' },
  { model='chino',       label='Albany Chino',              price=45000,  category='Muscle', dealer='bennys', desc='Classic Chicano lowrider.' },
  { model='chino2',      label='Albany Chino Custom',       price=130000, category='Muscle', dealer='bennys', desc='Custom Hydraulic lowrider.' },
  { model='clique',      label='Declasse Clique',           price=355000, category='Muscle', dealer='bennys', desc='Classic roadster horodrod.' },
  { model='dominator',   label='Vapid Dominator',           price=35000,  category='Muscle', dealer='bennys', desc='American muscle pony car.' },
  { model='dominator2',  label='Vapid Dominator GTX',       price=110000, category='Muscle', dealer='bennys', desc='Supercharged Dominator.' },
  { model='dominator3',  label='Vapid Dominator ASP',       price=1365000,category='Muscle', dealer='bennys', desc='Full race-spec ASP.' },
  { model='faction',     label='Willard Faction',           price=35000,  category='Muscle', dealer='bennys', desc='Classic American lowrider.' },
  { model='faction2',    label='Willard Faction Custom',    price=120000, category='Muscle', dealer='bennys', desc='Custom hydraulic lowrider.' },
  { model='felony',      label='Declasse Tulip M-100',      price=1795000,category='Muscle', dealer='bennys', desc='Track muscle sleeper.' },
  { model='gauntlet',    label='Bravado Gauntlet',          price=32000,  category='Muscle', dealer='bennys', desc='Dodge Challenger-style beast.' },
  { model='gauntlet2',   label='Bravado Gauntlet Classic',  price=745000, category='Muscle', dealer='bennys', desc='Classic 1970s muscle.' },
  { model='gauntlet3',   label='Bravado Gauntlet Classic Custom',price=785000,category='Muscle',dealer='bennys',desc='Restored classic muscle.' },
  { model='gauntlet4',   label='Bravado Hellfire',          price=1995000,category='Muscle', dealer='bennys', desc='Demonic supercharged muscle.' },
  { model='hotknife',    label='Vapid Hotknife',            price=90000,  category='Muscle', dealer='bennys', desc='Rat rod with style.' },
  { model='hustler',     label='Vapid Hustler',             price=395000, category='Muscle', dealer='bennys', desc='Bespoke horod from the 30s.' },
  { model='impaler',     label='Declasse Impaler',          price=135000, category='Muscle', dealer='bennys', desc='Classic American barge.' },
  { model='impaler2',    label='Declasse Impaler LX',       price=1285000,category='Muscle', dealer='bennys', desc='Track-prepped Impaler.' },
  { model='imperator',   label='Declasse Imperator',        price=795000, category='Muscle', dealer='bennys', desc='Road warrior muscle.' },
  { model='nightshade',  label='Vapid Nightshade',          price=745000, category='Muscle', dealer='bennys', desc='Retro muscle refined.' },
  { model='phoenix',     label='Imponte Phoenix',           price=26000,  category='Muscle', dealer='bennys', desc='Classic Trans Am-style.' },
  { model='ruiner',      label='Imponte Ruiner',            price=17000,  category='Muscle', dealer='bennys', desc='Budget muscle classic.' },
  { model='ruiner2',     label='Imponte Ruiner 2000',       price=5745600,category='Muscle', dealer='bennys', desc='Armed muscle from the future.' },
  { model='sabregt',     label='Declasse Sabre Turbo',      price=18000,  category='Muscle', dealer='bennys', desc='70s muscle workhorse.' },
  { model='sabregt2',    label='Declasse Sabre Turbo Custom',price=80000, category='Muscle', dealer='bennys', desc='Custom Sabre lowrider.' },
  { model='stallion',    label='Mustang Classic',           price=23000,  category='Muscle', dealer='bennys', desc='The American pony.' },
  { model='tampa',       label='Declasse Tampa',            price=32000,  category='Muscle', dealer='bennys', desc='Drift-ready muscle.' },
  { model='tampa3',      label='Declasse Drift Tampa',      price=1295000,category='Muscle', dealer='bennys', desc='Race-prepped drift machine.' },
  { model='tulip',       label='Declasse Tulip',            price=41000,  category='Muscle', dealer='bennys', desc='Old school American salon.' },
  { model='vigero',      label='Declasse Vigero',           price=22000,  category='Muscle', dealer='bennys', desc='Classic Camaro-style.' },
  { model='vigero2',     label='Declasse Vigero ZX',        price=1900000,category='Muscle', dealer='bennys', desc='Modern Vigero muscle track car.' },
  { model='voodoo2',     label='Willard Voodoo Custom',     price=120000, category='Muscle', dealer='bennys', desc='Lowrider custom build.' },

  -- ══ SEDANS / ECONOMY ══
  { model='asea',        label='Declasse Asea',             price=8000,   category='Sedan', dealer='southern', desc='Budget hatchback.' },
  { model='asterope',    label='Maibatsu Penumbra',         price=24000,  category='Sedan', dealer='southern', desc='Japanese commuter saloon.' },
  { model='cog55',       label='Obey Tailgater S',          price=915000, category='Sedan', dealer='southern', desc='Executive luxury saloon.' },
  { model='cognoscenti', label='Benefactor Cognoscenti',    price=251000, category='Sedan', dealer='southern', desc='German executive saloon.' },
  { model='cognoscenti2',label='Benefactor Cognoscenti 55', price=325000, category='Sedan', dealer='southern', desc='Stretched executive class.' },
  { model='emperor',     label='Albany Emperor',            price=8000,   category='Sedan', dealer='southern', desc='Elderly American cruiser.' },
  { model='fugitive',    label='Cheval Fugitive',           price=25000,  category='Sedan', dealer='southern', desc='Mid-size American family saloon.' },
  { model='glendale',    label='Albany Glendale',           price=9000,   category='Sedan', dealer='southern', desc='Old American luxury.' },
  { model='ingot',       label='Vulcar Ingot',              price=9000,   category='Sedan', dealer='southern', desc='Swedish reliable saloon.' },
  { model='intruder',    label='Karin Intruder',            price=15000,  category='Sedan', dealer='southern', desc='Japanese police-spec saloon.' },
  { model='merit',       label='Cheval Merit',              price=8500,   category='Sedan', dealer='southern', desc='Standard family sedan.' },
  { model='oracle',      label='Übermacht Oracle',          price=80000,  category='Sedan', dealer='southern', desc='German executive comfort.' },
  { model='oracle2',     label='Übermacht Oracle XS',       price=76000,  category='Sedan', dealer='southern', desc='Sports-tuned Oracle.' },
  { model='premier',     label='Declasse Premier',          price=12000,  category='Sedan', dealer='southern', desc='Classic LS police car.' },
  { model='primo',       label='Albany Primo',              price=10000,  category='Sedan', dealer='southern', desc='Budget saloon.' },
  { model='primo2',      label='Albany Primo Custom',       price=45000,  category='Sedan', dealer='southern', desc='Lowrider-tuned Primo.' },
  { model='schafter2',   label='Benefactor Schafter',       price=60000,  category='Sedan', dealer='southern', desc='German sports saloon.' },
  { model='schafter3',   label='Benefactor Schafter V12',   price=325000, category='Sedan', dealer='southern', desc='Top-spec V12 saloon.' },
  { model='stafford',    label='Buckingham Stafford',       price=425000, category='Sedan', dealer='southern', desc='British chauffeur-class luxury.' },
  { model='stanier',     label='Cheval Stanier',            price=12000,  category='Sedan', dealer='southern', desc='Standard American sedan.' },
  { model='superd',      label='Benefactor Superd',         price=195000, category='Sedan', dealer='southern', desc='German luxury flagship.' },
  { model='surge',       label='Dinka Surge',               price=18000,  category='Economy',dealer='southern',desc='Compact electric city car.' },
  { model='tailgater',   label='Obey Tailgater',            price=65000,  category='Sedan', dealer='southern', desc='Audi-style executive.' },
  { model='warrener',    label='Albany Warrener',           price=11000,  category='Sedan', dealer='southern', desc='Classic American barge.' },
  { model='washington',  label='Albany Washington',         price=18000,  category='Sedan', dealer='southern', desc='Presidential American saloon.' },

  -- ══ SUVs ══
  { model='baller',      label='Gallivanter Baller',        price=65000,  category='SUV', dealer='southern', desc='Luxury British SUV.' },
  { model='baller2',     label='Gallivanter Baller LE',     price=90000,  category='SUV', dealer='southern', desc='Armoured luxury SUV.' },
  { model='baller3',     label='Gallivanter Baller II',     price=130000, category='SUV', dealer='southern', desc='Second gen luxury Baller.' },
  { model='bjxl',        label='Canis Bodhi',               price=45000,  category='SUV', dealer='southern', desc='Classic American SUV.' },
  { model='cavalcade',   label='Albany Cavalcade',          price=28000,  category='SUV', dealer='southern', desc='Large American SUV.' },
  { model='cavalcade2',  label='Albany Cavalcade FXT',      price=32000,  category='SUV', dealer='southern', desc='Updated Cavalcade.' },
  { model='dubsta',      label='Benefactor Dubsta',         price=130000, category='SUV', dealer='southern', desc='German G-Wagen style.' },
  { model='dubsta2',     label='Benefactor Dubsta 6x6',     price=899000, category='SUV', dealer='southern', desc='6-wheel German off-roader.' },
  { model='fq2',         label='Obey Rocoto',               price=57000,  category='SUV', dealer='southern', desc='German premium SUV.' },
  { model='granger',     label='Declasse Granger',          price=28000,  category='SUV', dealer='southern', desc='Large American pickup SUV.' },
  { model='gresley',     label='Canis Gresley',             price=32000,  category='SUV', dealer='southern', desc='Classic British Land Rover.' },
  { model='habanero',    label='Canis Mesa',                price=25000,  category='SUV', dealer='southern', desc='Off-road capable SUV.' },
  { model='huntley',     label='Enus Huntley S',            price=125000, category='SUV', dealer='southern', desc='British luxury SUV.' },
  { model='iwagen',      label='Pfister Astron',            price=1800000,category='SUV', dealer='southern', desc='German electric luxury SUV.' },
  { model='kamacho',     label='Canis Kamacho',             price=350000, category='SUV', dealer='southern', desc='Baja off-road SUV.' },
  { model='landstalker', label='Canis Landstalker',         price=27000,  category='SUV', dealer='southern', desc='Classic LS outdoors SUV.' },
  { model='landstalker2',label='Canis Landstalker XL',      price=755000, category='SUV', dealer='southern', desc='Premium extended Landstalker.' },
  { model='novak',       label='Benefactor Novak',          price=1675000,category='SUV', dealer='southern', desc='Off-road focused German SUV.' },
  { model='patriot',     label='Canis Patriot',             price=55000,  category='SUV', dealer='southern', desc='American patriot spec SUV.' },
  { model='patriot2',    label='Canis Patriot Stretch',     price=235000, category='SUV', dealer='southern', desc='Stretched limo SUV.' },
  { model='peninsula',   label='Enus Jubilee',              price=455000, category='SUV', dealer='southern', desc='British royal SUV.' },
  { model='radi',        label='Vapid Radius',              price=15000,  category='SUV', dealer='southern', desc='Basic American pickup.' },
  { model='rebla',       label='Obey Rebla GTS',            price=42000,  category='SUV', dealer='southern', desc='German compact luxury SUV.' },
  { model='rocoto',      label='Obey Rocoto',               price=57000,  category='SUV', dealer='southern', desc='Compact crossover.' },
  { model='seminole',    label='Canis Seminole',            price=28000,  category='SUV', dealer='southern', desc='Jeep Cherokee-style.' },
  { model='seminole2',   label='Canis Seminole Frontier',   price=445000, category='SUV', dealer='southern', desc='Off-road Seminole build.' },
  { model='serrano',     label='Canis Serrano',             price=32000,  category='SUV', dealer='southern', desc='Budget SUV crossover.' },
  { model='toros',       label='Übermacht Toros',           price=495000, category='SUV', dealer='southern', desc='German big SUV.' },
  { model='xls',         label='Enus Cognoscenti Cabrio',   price=135000, category='SUV', dealer='southern', desc='British luxury convertible SUV.' },

  -- ══ MOTORCYCLES ══
  { model='akuma',       label='Dinka Akuma',               price=9000,   category='Motorcycle', dealer='lscycles', desc='Naked JDM streetfighter.' },
  { model='avarus',      label='LCC Avarus',                price=105000, category='Motorcycle', dealer='lscycles', desc='American bobber custom.' },
  { model='bagger',      label='Western Bagger',            price=82000,  category='Motorcycle', dealer='lscycles', desc='Classic American cruiser.' },
  { model='bati',        label='Dinka Bati 801',            price=15000,  category='Motorcycle', dealer='lscycles', desc='Sportbike standard.' },
  { model='bati2',       label='Dinka Bati 801RR',          price=19000,  category='Motorcycle', dealer='lscycles', desc='Race-trim Bati.' },
  { model='bf400',       label='Maibatsu Sanchez',          price=12000,  category='Motorcycle', dealer='lscycles', desc='Dirt bike / enduro.' },
  { model='chimera',     label='Nagasaki Chimera',          price=225000, category='Motorcycle', dealer='lscycles', desc='Adventure touring bike.' },
  { model='cliffhanger', label='Western Cliffhanger',       price=160000, category='Motorcycle', dealer='lscycles', desc='KTM-style off-road beast.' },
  { model='daemon',      label='Western Daemon',            price=82000,  category='Motorcycle', dealer='lscycles', desc='Classic outlaw chopper.' },
  { model='defiler',     label='Pegassi Defiler',           price=269000, category='Motorcycle', dealer='lscycles', desc='Aggressive Italian sportbike.' },
  { model='diablous',    label='Principe Diablous',         price=165000, category='Motorcycle', dealer='lscycles', desc='Italian design, raked forks.' },
  { model='diablous2',   label='Principe Diablous Custom',  price=180000, category='Motorcycle', dealer='lscycles', desc='Custom Diablous variant.' },
  { model='double',      label='Western Powersurge',        price=275000, category='Motorcycle', dealer='lscycles', desc='Electric motorcycle.' },
  { model='enduro',      label='Shitzu Enduro',             price=15000,  category='Motorcycle', dealer='lscycles', desc='Budget dual-sport.' },
  { model='esskey',      label='Pegassi Esskey',            price=420000, category='Motorcycle', dealer='lscycles', desc='Super sportbike.' },
  { model='faggio',      label='Pegassi Faggio',            price=5000,   category='Motorcycle', dealer='lscycles', desc='Classic Italian scooter.' },
  { model='faggio2',     label='Pegassi Faggio Mod',        price=7000,   category='Motorcycle', dealer='lscycles', desc='Modded scooter.' },
  { model='faggio3',     label='Pegassi Faggio Sport',      price=12000,  category='Motorcycle', dealer='lscycles', desc='Sporty scooter.' },
  { model='fcr',         label='LCC Innovation',            price=80000,  category='Motorcycle', dealer='lscycles', desc='Vintage cafe racer.' },
  { model='fcr2',        label='LCC Innovation Custom',     price=95000,  category='Motorcycle', dealer='lscycles', desc='Custom cafe racer.' },
  { model='gargoyle',    label='Nagasaki Gargoyle',         price=120000, category='Motorcycle', dealer='lscycles', desc='Streetfighter stance.' },
  { model='hakuchou',    label='Shitzu Hakuchou',           price=82000,  category='Motorcycle', dealer='lscycles', desc='Japanese superbike.' },
  { model='hakuchou2',   label='Shitzu Hakuchou Drag',      price=976000, category='Motorcycle', dealer='lscycles', desc='Drag-spec Hakuchou.' },
  { model='hexer',       label='Western Hexer',             price=80000,  category='Motorcycle', dealer='lscycles', desc='Outlaw custom cruiser.' },
  { model='innovation',  label='LCC Innovation',            price=80000,  category='Motorcycle', dealer='lscycles', desc='Vintage café racer.' },
  { model='manchez',     label='Maibatsu Manchez',          price=8000,   category='Motorcycle', dealer='lscycles', desc='Trail bike.' },
  { model='nemesis',     label='Western Nemesis',           price=12000,  category='Motorcycle', dealer='lscycles', desc='Classic streetbike.' },
  { model='nightblade',  label='Western Nightblade',        price=100000, category='Motorcycle', dealer='lscycles', desc='Chopper custom.' },
  { model='oppressor',   label='Pegassi Oppressor',         price=3524500,category='Motorcycle', dealer='lscycles', desc='Rocket-boosted motorbike.' },
  { model='oppressor2',  label='Pegassi Oppressor Mk II',   price=3890250,category='Motorcycle', dealer='lscycles', desc='Flying weaponized hoverbike.' },
  { model='pcj',         label='Dinka PCJ 600',             price=10000,  category='Motorcycle', dealer='lscycles', desc='Classic sportbike for stunts.' },
  { model='ruffian',     label='Shitzu Ruffian',            price=10000,  category='Motorcycle', dealer='lscycles', desc='Budget naked streetbike.' },
  { model='sanchez',     label='Maibatsu Sanchez',          price=8000,   category='Motorcycle', dealer='lscycles', desc='Motocross champion.' },
  { model='sanchez2',    label='Maibatsu Sanchez Livery',   price=9000,   category='Motorcycle', dealer='lscycles', desc='Livery dirt bike.' },
  { model='sovereign',   label='Western Sovereign',         price=10000,  category='Motorcycle', dealer='lscycles', desc='Classic cruiser.' },
  { model='stryder',     label='Western Stryder',           price=500000, category='Motorcycle', dealer='lscycles', desc='Electric bicycle.' },
  { model='thrust',      label='Principe Lectro',           price=38000,  category='Motorcycle', dealer='lscycles', desc='Electric superbike.' },
  { model='vader',       label='Shitzu Vader',              price=9000,   category='Motorcycle', dealer='lscycles', desc='Budget sportbike.' },
  { model='vindicator',  label='Nagasaki Vindicator',       price=27000,  category='Motorcycle', dealer='lscycles', desc='Adventure tourer.' },
  { model='vortex',      label='Pegassi Vortex',            price=28000,  category='Motorcycle', dealer='lscycles', desc='Italian sportbike.' },
  { model='wolfsbane',   label='Western Wolfsbane',         price=170000, category='Motorcycle', dealer='lscycles', desc='Classic bobber.' },
  { model='zombiea',     label='Western Zombie Chopper',    price=75000,  category='Motorcycle', dealer='lscycles', desc='Post-apocalyptic custom.' },
  { model='zombieb',     label='Western Zombie Bobber',     price=75000,  category='Motorcycle', dealer='lscycles', desc='Bobber-style custom.' },

  -- ══ VANS ══
  { model='bison',       label='Vapid Bison',               price=20000,  category='Van', dealer='southern', desc='Standard pickup truck.' },
  { model='bobcatxl',    label='Vapid Bobcat XL',           price=18000,  category='Van', dealer='southern', desc='Utility pickup truck.' },
  { model='boxville2',   label='Brute Boxville',            price=14000,  category='Van', dealer='patriot', desc='Delivery box van.' },
  { model='burrito',     label='Declasse Burrito',          price=16000,  category='Van', dealer='patriot', desc='Classic panel van.' },
  { model='gburrito2',   label='Gang Burrito',              price=24000,  category='Van', dealer='patriot', desc='Gang-spec burrito van.' },
  { model='minivan',     label='Vapid Minivan',             price=28000,  category='Van', dealer='southern', desc='Family minivan.' },
  { model='pony',        label='Brute Pony',                price=8000,   category='Van', dealer='patriot', desc='Budget cargo van.' },
  { model='rumpo',       label='Bravado Rumpo',             price=20000,  category='Van', dealer='patriot', desc='Custom low-roof van.' },
  { model='rumpo2',      label='Bravado Rumpo Custom',      price=45000,  category='Van', dealer='patriot', desc='Bespoke custom Rumpo.' },
  { model='surfer',      label='Declasse Lifeguard',        price=15000,  category='Van', dealer='southern', desc='Beach-spec Ford Econoline.' },
  { model='youga',       label='Declasse Youga',            price=13000,  category='Van', dealer='patriot', desc='Vanning icon.' },
  { model='youga2',      label='Declasse Youga Classic',    price=17000,  category='Van', dealer='patriot', desc='Retro Youga custom.' },

  -- ══ TRUCKS / COMMERCIAL ══
  { model='biff',        label='HVY Biff',                  price=40000,  category='Commercial', dealer='patriot', desc='Big rig cab.' },
  { model='hauler',      label='Jobuilt Hauler',            price=32000,  category='Commercial', dealer='patriot', desc='Long-haul cab.' },
  { model='mule',        label='Brute Mule',                price=25000,  category='Commercial', dealer='patriot', desc='Classic box truck.' },
  { model='mule3',       label='Brute Mule Custom',         price=55000,  category='Commercial', dealer='patriot', desc='Custom Mule box truck.' },
  { model='packer',      label='HVY Packer',                price=60000,  category='Truck', dealer='patriot', desc='Car transport hauler.' },
  { model='phantom',     label='Jobuilt Phantom',           price=90000,  category='Commercial', dealer='patriot', desc='Classic semi truck.' },
  { model='phantom2',    label='Jobuilt Phantom Custom',    price=2785000,category='Commercial', dealer='patriot', desc='Custom-built Phantom.' },
  { model='pounder',     label='HVY Pounder',               price=35000,  category='Commercial', dealer='patriot', desc='Heavy dump truck.' },
  { model='stockade',    label='Brute Stockade',            price=55000,  category='Commercial', dealer='patriot', desc='Armoured transport.' },
  { model='rebel',       label='Canis Mesa',                price=22000,  category='Truck', dealer='patriot', desc='Off-road pickup.' },
  { model='sandking',    label='Vapid Sandking XL',         price=42000,  category='Truck', dealer='patriot', desc='Desert baja truck.' },
  { model='sandking2',   label='Vapid Sandking SWB',        price=38000,  category='Truck', dealer='patriot', desc='Short wheelbase Sandking.' },

  -- ══ HELICOPTERS ══
  { model='akula',       label='Buckingham Akula',          price=3704050,category='Helicopter', dealer='elitas', desc='Stealth attack helicopter.' },
  { model='annihilator', label='HVY Annihilator',           price=1825000,category='Helicopter', dealer='elitas', desc='Armed military helicopter.' },
  { model='buzzard2',    label='Nagasaki Buzzard',          price=1750000,category='Helicopter', dealer='elitas', desc='Armed attack helicopter.' },
  { model='carbon',      label='Buckingham Carbon RS',      price=2195000,category='Helicopter', dealer='elitas', desc='Racing helicopter.' },
  { model='cargobob',    label='Cargobob',                  price=1786000,category='Helicopter', dealer='elitas', desc='Military cargo chopper.' },
  { model='frogger',     label='Buckingham Frogger',        price=1300000,category='Helicopter', dealer='elitas', desc='Civilian tour helicopter.' },
  { model='hunter',      label='FH-1 Hunter',               price=4123048,category='Helicopter', dealer='elitas', desc='Apache-style attack helo.' },
  { model='maverick',    label='Buckingham Maverick',       price=780000, category='Helicopter', dealer='elitas', desc='Standard civilian helicopter.' },
  { model='savage',      label='Nagasaki Buzzard Attack',   price=2123048,category='Helicopter', dealer='elitas', desc='Heavy attack helicopter.' },
  { model='seasparrow',  label='Buckingham Sea Sparrow',    price=1815000,category='Helicopter', dealer='elitas', desc='Armed amphibious helicopter.' },
  { model='supervolito', label='Buckingham Volatus',        price=2250000,category='Helicopter', dealer='elitas', desc='Luxury executive helicopter.' },
  { model='swift',       label='Buckingham Swift',          price=1500000,category='Helicopter', dealer='elitas', desc='Luxury touring helicopter.' },
  { model='swift2',      label='Buckingham Swift Deluxe',   price=5150000,category='Helicopter', dealer='elitas', desc='Top spec luxury helicopter.' },
  { model='valkyrie',    label='Nagasaki Valkyrie',         price=2750000,category='Helicopter', dealer='elitas', desc='Gunship military helicopter.' },
  { model='volatus',     label='Buckingham Volatus',        price=2250000,category='Helicopter', dealer='elitas', desc='Executive helicopter.' },

  -- ══ PLANES ══
  { model='alphaz1',     label='Jobuilt Velum',             price=735000, category='Plane', dealer='elitas', desc='Light propeller plane.' },
  { model='avenger',     label='Mammoth Avenger',           price=3995550,category='Plane', dealer='elitas', desc='Armed stealth aircraft.' },
  { model='besra',       label='Buckingham Besra',          price=1150000,category='Plane', dealer='elitas', desc='Jet trainer aircraft.' },
  { model='cuban800',    label='Cuban 800',                 price=240000, category='Plane', dealer='elitas', desc='Light propeller aircraft.' },
  { model='duster',      label='Grumman Duster',            price=275000, category='Plane', dealer='elitas', desc='Crop duster plane.' },
  { model='hydra',       label='Mammoth Hydra',             price=3990000,category='Plane', dealer='elitas', desc='VTOL military jet.' },
  { model='lazer',       label='P-996 Lazer',               price=6500000,category='Plane', dealer='elitas', desc='Top-tier military fighter jet.' },
  { model='luxor',       label='Buckingham Luxor',          price=1500000,category='Plane', dealer='elitas', desc='Executive private jet.' },
  { model='luxor2',      label='Buckingham Luxor Deluxe',   price=10000000,category='Plane',dealer='elitas', desc='Ultimate private jet.' },
  { model='miljet',      label='Buckingham Miljet',         price=1795000,category='Plane', dealer='elitas', desc='Private military jet.' },
  { model='nimbus',      label='Buckingham Nimbus',         price=1900000,category='Plane', dealer='elitas', desc='High-speed private jet.' },
  { model='nokota',      label='P-45 Nokota',               price=2896750,category='Plane', dealer='elitas', desc='WWII fighter plane.' },
  { model='pyro',        label='Buckingham Pyro',           price=4455500,category='Plane', dealer='elitas', desc='WWII attack fighter.' },
  { model='rogue',       label='Mammoth Rogue',             price=1596900,category='Plane', dealer='elitas', desc='Twin-boom armed plane.' },
  { model='seabreeze',   label='Maibatsu Seabreeze',        price=1130500,category='Plane', dealer='elitas', desc='Amphibious commuter plane.' },
  { model='shamal',      label='Buckingham Shamal',         price=1150000,category='Plane', dealer='elitas', desc='Mid-size executive jet.' },
  { model='strikeforce', label='Mammoth Strikeforce',       price=3800000,category='Plane', dealer='elitas', desc='Stealth fighter jet.' },
  { model='titan',       label='Jobuilt Titan',             price=2000000,category='Plane', dealer='elitas', desc='Military cargo plane.' },
  { model='velum',       label='Jobuilt Velum',             price=735000, category='Plane', dealer='elitas', desc='5-seater light plane.' },
  { model='vestra',      label='Buckingham Vestra',         price=900000, category='Plane', dealer='elitas', desc='Light executive jet.' },

  -- ══ BOATS ══
  { model='dinghy',      label='Nagasaki Dinghy',           price=12000,  category='Boat', dealer='boatclub', desc='Small rubber dinghy.' },
  { model='dinghy2',     label='Nagasaki Dinghy 2-seater',  price=15000,  category='Boat', dealer='boatclub', desc='2-seat dinghy.' },
  { model='jetmax',      label='Shitzu Jetmax',             price=195000, category='Boat', dealer='boatclub', desc='High-speed powerboat.' },
  { model='longfin',     label='Buckingham Longfin',        price=1615000,category='Boat', dealer='boatclub', desc='Super yacht speedboat.' },
  { model='marquis',     label='Buckingham Marquis',        price=125000, category='Boat', dealer='boatclub', desc='Luxury sailing yacht.' },
  { model='seashark',    label='Speedophile 2000',          price=25000,  category='Boat', dealer='boatclub', desc='Personal watercraft (jet ski).' },
  { model='speeder',     label='Shitzu Speeder',            price=305000, category='Boat', dealer='boatclub', desc='Racing powerboat.' },
  { model='squalo',      label='Shitzu Squalo',             price=160000, category='Boat', dealer='boatclub', desc='Open performance speedboat.' },
  { model='submersible', label='Kraken Submersible',        price=1325000,category='Boat', dealer='boatclub', desc='Mini submarine.' },
  { model='suntrap',     label='Buckingham Suntrap',        price=390000, category='Boat', dealer='boatclub', desc='Luxury yacht.' },
  { model='toro',        label='Shitzu Toro',               price=440000, category='Boat', dealer='boatclub', desc='Top speed powerboat.' },
  { model='toro2',       label='Shitzu Toro (Custom)',      price=480000, category='Boat', dealer='boatclub', desc='Custom racing powerboat.' },
  { model='tropic',      label='Speeder Tropic',            price=95000,  category='Boat', dealer='boatclub', desc='Leisure speedboat.' },
  { model='tropic2',     label='Speeder Tropic Enhanced',   price=120000, category='Boat', dealer='boatclub', desc='Enhanced leisure boat.' },
  { model='tug',         label='Tugboat',                   price=750000, category='Boat', dealer='boatclub', desc='Harbour tug boat.' },
}
