Config = {}

-- type: 'house' | 'business'
-- businessIncome: $ per 5 minutes (businesses only)
-- spawn: where player spawns when using this as home
Config.Properties = {
    -- ── Houses ──────────────────────────────────────────────────────────────────
    {
        id       = 'grove_house',
        label    = 'Grove Street House',
        type     = 'house',
        price    = 25000,
        blipPos  = vector3(108.0,  -1958.0, 21.2),
        spawn    = { x=108.5,  y=-1957.0, z=21.2,  h=190.0 },
        icon     = '🏠',
        desc     = 'Modest house in South LS. Great starter home.',
    },
    {
        id       = 'vinewood_bungalow',
        label    = 'Vinewood Bungalow',
        type     = 'house',
        price    = 95000,
        blipPos  = vector3(-654.0, 566.0,  131.0),
        spawn    = { x=-653.0, y=567.0,  z=131.0, h=340.0 },
        icon     = '🏡',
        desc     = 'Quiet hillside bungalow overlooking the city.',
    },
    {
        id       = 'sandy_trailer',
        label    = 'Sandy Shores Trailer',
        type     = 'house',
        price    = 12000,
        blipPos  = vector3(1969.0, 3792.0, 32.5),
        spawn    = { x=1969.5, y=3793.0, z=32.5, h=90.0  },
        icon     = '🏕️',
        desc     = 'Desert life out east. Cheap but cosy.',
    },
    {
        id       = 'beachside_apt',
        label    = 'Del Perro Apartment',
        type     = 'house',
        price    = 60000,
        blipPos  = vector3(-1447.0,-541.0, 34.0),
        spawn    = { x=-1446.0,y=-540.0, z=34.0, h=270.0 },
        icon     = '🏢',
        desc     = 'Beachside apartment with ocean views.',
    },
    {
        id       = 'rockford_mansion',
        label    = 'Rockford Hills Mansion',
        type     = 'house',
        price    = 450000,
        blipPos  = vector3(-863.0, 177.0,  73.0),
        spawn    = { x=-862.0, y=178.0,  z=73.0, h=130.0 },
        icon     = '🏰',
        desc     = 'Luxury mansion in the most exclusive neighbourhood.',
    },
    {
        id       = 'paleto_cottage',
        label    = 'Paleto Bay Cottage',
        type     = 'house',
        price    = 20000,
        blipPos  = vector3(-105.0, 6466.0, 31.6),
        spawn    = { x=-104.0, y=6467.0, z=31.6, h=45.0  },
        icon     = '🏘️',
        desc     = 'Peaceful coastal cottage up north.',
    },

    -- ── More Houses ──────────────────────────────────────────────────────────────
    {
        id       = 'murrieta_house',
        label    = 'Murrieta Heights House',
        type     = 'house',
        price    = 18000,
        blipPos  = vector3(870.0,  -2000.0, 29.5),
        spawn    = { x=871.0,  y=-1999.0, z=29.5, h=45.0  },
        icon     = '🏠',
        desc     = 'Working class home in East LS. Affordable starter.',
    },
    {
        id       = 'chumash_villa',
        label    = 'Chumash Beach Villa',
        type     = 'house',
        price    = 180000,
        blipPos  = vector3(-3046.0, 89.0, 11.2),
        spawn    = { x=-3045.0, y=90.0,  z=11.2, h=90.0  },
        icon     = '🏖️',
        desc     = 'Stylish villa right on the Pacific coast.',
    },
    {
        id       = 'mirror_park_loft',
        label    = 'Mirror Park Loft',
        type     = 'house',
        price    = 72000,
        blipPos  = vector3(1257.0, -756.0,  57.5),
        spawn    = { x=1258.0, y=-755.0, z=57.5, h=180.0 },
        icon     = '🏙️',
        desc     = 'Trendy loft with skyline views in Mirror Park.',
    },
    {
        id       = 'vespucci_apt',
        label    = 'Vespucci Apartment',
        type     = 'house',
        price    = 55000,
        blipPos  = vector3(-1068.0,-694.0,  26.0),
        spawn    = { x=-1067.0,y=-693.0, z=26.0, h=270.0 },
        icon     = '🏢',
        desc     = 'Art deco apartment in bohemian Vespucci.',
    },
    {
        id       = 'strawberry_rowhouse',
        label    = 'Strawberry Row House',
        type     = 'house',
        price    = 30000,
        blipPos  = vector3(71.0,  -1597.0, 29.3),
        spawn    = { x=72.0,  y=-1596.0, z=29.3, h=0.0   },
        icon     = '🏘️',
        desc     = 'Classic row house in the heart of Strawberry.',
    },
    {
        id       = 'grapeseed_farmhouse',
        label    = 'Grapeseed Farmhouse',
        type     = 'house',
        price    = 38000,
        blipPos  = vector3(1683.0, 4832.0, 42.1),
        spawn    = { x=1684.0, y=4833.0, z=42.1, h=135.0 },
        icon     = '🌾',
        desc     = 'Spacious farmhouse in the countryside. Fresh air included.',
    },
    {
        id       = 'eclipse_penthouse',
        label    = 'Eclipse Blvd Penthouse',
        type     = 'house',
        price    = 320000,
        blipPos  = vector3(-762.0, 322.0,  83.0),
        spawn    = { x=-761.0, y=323.0,  z=83.0, h=200.0 },
        icon     = '🏰',
        desc     = 'Glass penthouse towering above Vinewood West.',
    },

    -- ── Businesses ───────────────────────────────────────────────────────────────
    {
        id             = 'corner_shop',
        label          = 'Corner Shop',
        type           = 'business',
        price          = 45000,
        blipPos        = vector3(28.0,  -1346.0, 29.0),
        spawn          = { x=29.0,  y=-1345.0, z=29.0, h=90.0 },
        icon           = '🏪',
        desc           = 'Small convenience store in South LS.',
        businessIncome = 250,   -- $250 every 5 min while logged in
    },
    {
        id             = 'car_wash',
        label          = 'Car Wash',
        type           = 'business',
        price          = 80000,
        blipPos        = vector3(-697.0,-933.0,  19.2),
        spawn          = { x=-696.0,y=-932.0, z=19.2, h=200.0 },
        icon           = '🚗',
        desc           = 'Popular car wash in Rockford Hills.',
        businessIncome = 400,
    },
    {
        id             = 'auto_shop',
        label          = 'Auto Repair Shop',
        type           = 'business',
        price          = 120000,
        blipPos        = vector3(516.0, -1316.0, 29.0),
        spawn          = { x=517.0, y=-1315.0, z=29.0, h=0.0   },
        icon           = '🔧',
        desc           = 'Busy mechanic shop near LSIA.',
        businessIncome = 600,
    },
    {
        id             = 'nightclub',
        label          = 'Eonexis Nightclub',
        type           = 'business',
        price          = 750000,
        blipPos        = vector3(-1603.0,-3005.0,13.9),
        spawn          = { x=-1602.0,y=-3004.0,z=13.9, h=135.0 },
        icon           = '🎶',
        desc           = 'High-end nightclub. Best earner on the block.',
        businessIncome = 1500,
    },
    {
        id             = 'gas_station',
        label          = 'Gas Station',
        type           = 'business',
        price          = 55000,
        blipPos        = vector3(265.0,  -1261.0, 29.0),
        spawn          = { x=266.0,  y=-1260.0, z=29.0, h=90.0  },
        icon           = '⛽',
        desc           = 'Busy fuel station near the freeway.',
        businessIncome = 320,
    },
    {
        id             = 'barbershop',
        label          = 'Downtown Barbershop',
        type           = 'business',
        price          = 35000,
        blipPos        = vector3(-806.0, -184.0,  37.6),
        spawn          = { x=-805.0, y=-183.0, z=37.6, h=315.0 },
        icon           = '💈',
        desc           = 'Classic barbershop in downtown LS.',
        businessIncome = 180,
    },
    {
        id             = 'restaurant',
        label          = 'South LS Restaurant',
        type           = 'business',
        price          = 90000,
        blipPos        = vector3(150.0,  -1011.0, 29.3),
        spawn          = { x=151.0,  y=-1010.0, z=29.3, h=270.0 },
        icon           = '🍽️',
        desc           = 'Popular diner near the fashion district.',
        businessIncome = 450,
    },
    {
        id             = 'strip_club',
        label          = 'Vanilla Unicorn',
        type           = 'business',
        price          = 200000,
        blipPos        = vector3(127.0,  -1307.0, 29.2),
        spawn          = { x=128.0,  y=-1306.0, z=29.2, h=0.0   },
        icon           = '🦄',
        desc           = 'The most profitable adult venue in South LS.',
        businessIncome = 900,
    },
    {
        id             = 'laundromat',
        label          = 'Laundromat',
        type           = 'business',
        price          = 42000,
        blipPos        = vector3(-1225.0,-893.0,  12.0),
        spawn          = { x=-1224.0,y=-892.0, z=12.0, h=135.0 },
        icon           = '🧺',
        desc           = 'Nothing shady going on here. Just clean clothes.',
        businessIncome = 220,
    },
}

Config.MarkerType   = 1      -- cylinder marker
Config.MarkerRadius = 2.0    -- metres to trigger marker interaction
Config.IncomeInterval = 300000  -- 5 minutes in ms
