Config = {}
Config.DataFile = 'data/skilltree.json'

--[[
  Skill tree tiers. Each skill has:
    id         unique string
    label      display name
    desc       description shown in UI
    tier       1 = onboarding, 2 = intermediate, 3 = advanced
    reward     { cash=N }
    unlocks    text shown as the unlock reward
    auto       true = server can auto-complete (e.g. on join, on command)
    requires   list of skill IDs that must be done first
    blip       { pos, sprite, colour } — quest blip on map (nil = no blip)
               colours: 2=red(job), 26=purple(skill), 5=yellow
]]
Config.Skills = {
    -- ══ TIER 1: Server Onboarding ══
    {
        id       = 'welcome',
        label    = 'Welcome to Eonexis',
        desc     = 'Join the server for the first time. You\'re here!',
        tier     = 1,
        reward   = { cash = 500 },
        unlocks  = 'Daily Bonuses',
        auto     = true,
        requires = {},
        blip     = nil,
    },
    {
        id       = 'check_rules',
        label    = 'Read the Rules',
        desc     = 'Open the rules board. Press F2 or type /rules.',
        tier     = 1,
        reward   = { cash = 250 },
        unlocks  = 'Rule-aware citizen status',
        auto     = false,
        requires = { 'welcome' },
        blip     = nil,
    },
    {
        id       = 'check_balance',
        label    = 'Check Your Balance',
        desc     = 'Type /balance to see your cash and bank balance.',
        tier     = 1,
        reward   = { cash = 200 },
        unlocks  = 'Banking App',
        auto     = false,
        requires = { 'welcome' },
        blip     = nil,
    },
    {
        id       = 'open_phone',
        label    = 'Open Your Phone',
        desc     = 'Press P to open your Eonexis smartphone.',
        tier     = 1,
        reward   = { cash = 200 },
        unlocks  = 'Phone GPS',
        auto     = false,
        requires = { 'welcome' },
        blip     = nil,
    },
    {
        id       = 'first_job',
        label    = 'Get Your First Job',
        desc     = 'Visit the Job Center (yellow star, LSIA area) and pick any job.',
        tier     = 1,
        reward   = { cash = 750 },
        unlocks  = 'Work Command',
        auto     = false,
        requires = { 'check_balance' },
        blip     = { pos=vector3(128.0,-1043.0,29.0), sprite=436, colour=5, label='Job Center' },
    },
    {
        id       = 'first_task',
        label    = 'Complete a Job Task',
        desc     = 'Type /work and complete your first task for pay.',
        tier     = 1,
        reward   = { cash = 1000 },
        unlocks  = 'Bonus job pay (+5%)',
        auto     = false,
        requires = { 'first_job' },
        blip     = nil,
    },
    {
        id       = 'visit_garage',
        label    = 'Visit the Garage',
        desc     = 'Go to the vehicle garage in Rockford Hills (green marker).',
        tier     = 1,
        reward   = { cash = 300 },
        unlocks  = 'Garage Access',
        auto     = false,
        requires = { 'open_phone' },
        blip     = { pos=vector3(-351.0,-133.0,39.0), sprite=357, colour=26, label='Vehicle Garage' },
    },
    {
        id       = 'visit_dealership',
        label    = 'Visit the Dealership',
        desc     = 'Check out Premium Deluxe Motorsport (yellow marker near PDM).',
        tier     = 1,
        reward   = { cash = 300 },
        unlocks  = 'Vehicle Discounts (future)',
        auto     = false,
        requires = { 'visit_garage' },
        blip     = { pos=vector3(-46.0,-1097.0,26.0), sprite=326, colour=5, label='Dealership' },
    },
    {
        id       = 'visit_shop',
        label    = 'Visit a 24/7 Store',
        desc     = 'Find any 24/7 convenience store and buy something.',
        tier     = 1,
        reward   = { cash = 250 },
        unlocks  = 'Shop Discounts (future)',
        auto     = false,
        requires = { 'welcome' },
        blip     = { pos=vector3(-714.9,-909.3,19.2), sprite=52, colour=2, label='24/7 Store' },
    },
    {
        id       = 'daily_checkin',
        label    = 'Claim Daily Bonus',
        desc     = 'Log in two days in a row to claim your streak bonus.',
        tier     = 1,
        reward   = { cash = 500 },
        unlocks  = 'Streak Multiplier',
        auto     = false,
        requires = { 'welcome' },
        blip     = nil,
    },

    -- ══ TIER 2: Getting Established ══
    {
        id       = 'earn_5k',
        label    = 'Earn $5,000',
        desc     = 'Accumulate $5,000 total cash through jobs or bonuses.',
        tier     = 2,
        reward   = { cash = 1500 },
        unlocks  = 'Bank Interest (future)',
        auto     = false,
        requires = { 'first_task' },
        blip     = nil,
    },
    {
        id       = 'buy_vehicle',
        label    = 'Buy Your First Vehicle',
        desc     = 'Purchase any vehicle from the dealership.',
        tier     = 2,
        reward   = { cash = 2000 },
        unlocks  = 'Garage slot upgrade (2 vehicles)',
        auto     = false,
        requires = { 'visit_dealership', 'earn_5k' },
        blip     = nil,
    },
    {
        id       = 'try_casino',
        label    = 'Try the Lucky Wheel',
        desc     = 'Spin the Lucky Wheel at the casino (Diamond Casino area).',
        tier     = 2,
        reward   = { cash = 500 },
        unlocks  = 'Casino VIP hint',
        auto     = false,
        requires = { 'earn_5k' },
        blip     = { pos=vector3(897.0,48.0,81.0), sprite=404, colour=46, label='Lucky Wheel Casino' },
    },
    {
        id       = 'buy_property',
        label    = 'Buy a Property',
        desc     = 'Purchase a house or business from the property market.',
        tier     = 2,
        reward   = { cash = 3000 },
        unlocks  = 'Home spawn point',
        auto     = false,
        requires = { 'earn_5k' },
        blip     = nil,
    },
    {
        id       = 'complete_5_tasks',
        label    = 'Complete 5 Job Tasks',
        desc     = 'Finish 5 total job tasks across any jobs.',
        tier     = 2,
        reward   = { cash = 2500 },
        unlocks  = 'Elite Worker title (future)',
        auto     = false,
        requires = { 'first_task' },
        blip     = nil,
    },

    -- ══ TIER 2 continued ══
    {
        id       = 'link_discord',
        label    = 'Link Discord',
        desc     = 'Use /link in-game and verify in Discord to link your account.',
        tier     = 2,
        reward   = { cash = 2000 },
        unlocks  = 'Discord daily bonus + DM notifications',
        auto     = false,
        requires = { 'welcome' },
        blip     = nil,
    },
    {
        id       = 'buy_license',
        label    = 'Get a Job License',
        desc     = 'Purchase any job license at its office location on the map.',
        tier     = 2,
        reward   = { cash = 1500 },
        unlocks  = 'Access to licensed high-pay jobs',
        auto     = false,
        requires = { 'first_task' },
        blip     = { pos=vector3(-424.0,-597.0,30.5), sprite=380, colour=5, label='DMV — Buy a License' },
    },
    {
        id       = 'try_fishing',
        label    = 'Gone Fishin\'',
        desc     = 'Buy a fishing license and complete a fishing task.',
        tier     = 2,
        reward   = { cash = 1000 },
        unlocks  = 'Fishing XP bonus',
        auto     = false,
        requires = { 'buy_license' },
        blip     = { pos=vector3(-764.0,-1538.0,0.5), sprite=68, colour=3, label='Harbor — Fishing License' },
    },
    {
        id       = 'use_inventory',
        label    = 'Use Your Inventory',
        desc     = 'Open /inv and use a consumable item.',
        tier     = 2,
        reward   = { cash = 300 },
        unlocks  = 'Extra inventory slot',
        auto     = false,
        requires = { 'visit_shop' },
        blip     = nil,
    },

    -- ══ TIER 3: Advanced ══
    {
        id       = 'earn_50k',
        label    = 'Earn $50,000',
        desc     = 'Reach $50,000 total cash.',
        tier     = 3,
        reward   = { cash = 10000 },
        unlocks  = 'VIP player aura (purple nameplate glow)',
        auto     = false,
        requires = { 'earn_5k', 'buy_vehicle' },
        blip     = nil,
    },
    {
        id       = 'own_business',
        label    = 'Own a Business',
        desc     = 'Buy one of the business properties and earn passive income.',
        tier     = 3,
        reward   = { cash = 5000 },
        unlocks  = 'Business income +10% passive bonus',
        auto     = false,
        requires = { 'buy_property', 'earn_50k' },
        blip     = nil,
    },
    {
        id       = 'complete_tier1',
        label    = 'Tier 1 Master',
        desc     = 'Complete all Tier 1 onboarding skills.',
        tier     = 3,
        reward   = { cash = 5000 },
        unlocks  = 'Tier 1 Master title + golden chat prefix',
        auto     = false,
        requires = { 'welcome','check_rules','check_balance','open_phone','first_job','first_task','visit_garage','visit_dealership','visit_shop','daily_checkin' },
        blip     = nil,
    },
    {
        id       = 'complete_10_tasks',
        label    = 'Grind Master',
        desc     = 'Complete 10 total job tasks.',
        tier     = 3,
        reward   = { cash = 4000 },
        unlocks  = 'Job task payout +10%',
        auto     = false,
        requires = { 'complete_5_tasks' },
        blip     = nil,
    },
    {
        id       = 'all_licenses',
        label    = 'License Collection',
        desc     = 'Own all 5 job licenses.',
        tier     = 3,
        reward   = { cash = 8000 },
        unlocks  = 'All Jobs unlocked + Pro Worker tag',
        auto     = false,
        requires = { 'buy_license' },
        blip     = nil,
    },
    {
        id       = 'property_mogul',
        label    = 'Property Mogul',
        desc     = 'Own 3 or more properties at the same time.',
        tier     = 3,
        reward   = { cash = 15000 },
        unlocks  = 'Mogul title + property income +15%',
        auto     = false,
        requires = { 'own_business' },
        blip     = nil,
    },
    {
        id       = 'street_king',
        label    = 'Street King',
        desc     = 'Win 3 street races.',
        tier     = 3,
        reward   = { cash = 6000 },
        unlocks  = 'Race start boost (head start in future races)',
        auto     = false,
        requires = { 'visit_dealership' },
        blip     = nil,
    },
    {
        id       = 'casino_whale',
        label    = 'Casino Whale',
        desc     = 'Win over $5,000 total at the casino.',
        tier     = 3,
        reward   = { cash = 7500 },
        unlocks  = 'Casino VIP seat (better odds)',
        auto     = false,
        requires = { 'try_casino' },
        blip     = { pos=vector3(897.0,48.0,81.0), sprite=404, colour=46, label='Diamond Casino' },
    },
}
